# Generated by Django 4.1.6 on 2023-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_delete_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
