# Generated by Django 4.1.6 on 2023-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_id_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
